apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.6.4

resources:
- https://github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.6.4
- cmp-plugin.yaml

patchesStrategicMerge:
- argocd-repo-server.yaml
