apiVersion: v1
kind: Secret
metadata:
    name: encrypt-secret
    namespace: argocd
type: Opaque
data:
    key: ENC[AES256_GCM,data:ZIdRLg==,iv:g3U2xmBamZf8hE7B1FcA0S5tlul7MXHMDU5B6kfozRA=,tag:behUZHWR2IEWMuJ0WOPErg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T08:17:05Z"
    mac: ENC[AES256_GCM,data:QH10LUYo05vPWRM/PoENPVPQHrmopEoraPerl3S/TrW8s4PuQInNaiDUgnh4UiScgVknMyovfBNlvIb7VUyC9R6Cve7r/R5XusNrhfABRPYhEQGODxNry1lj22mlAvnCfRS1olvSvUWIoTn0Acije8K0vfWo7PQ9amCCYG2tqcM=,iv:kgQFDVxs761FUzqCYTqQQwjGvS5K2owv/OrbYHUvuEs=,tag:2pRcoaYORv++9e1ShULKbA==,type:str]
    pgp:
        - created_at: "2025-01-28T08:17:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxofeBydO/LtAQ//ZhevFaOZHPXhV1aO6Y9Ig4S5wxgZgcxNiAy8erplDuxl
            Pcee1b0/MYWINVkXATfERRCEfJBdJNp2jfywBP4aVFx171dNxQ1c032MseXEFOlD
            PC4h0UoJaIKpfK7idP2EC94UTpgWPHNHr40m6h2VEb2rUujwXZOihAFF8fKHVfhh
            507qom7zUXdnmye2RtGtoY3CkcZa85VK4ARX+siXTTlXkSsW/gwhaeXYWNct2caj
            JVKBLybo+169Qj2ERIKH9VEn0HTLTAgT1DBcS8lsxQX+a9q+zRg/Mfvmhsac5GQN
            1Fe5xWoLPy2znXOFQwgVUp7FzjcynL8036PQfnxPmB8+Ak7zVWj2TaRnbSeOlvit
            hYjl+Pr7pAxhSnkO6nmZJBKENm3ZdEPAFMVVNIVgw8LcWDeqoOjEIDYayKVm95wV
            UpYt+k6Y2J1Nvfb0UuD2H0LvXDT3DzfvVjV/X0hJvE+4Wg4sVcgdlETZVXegZE5K
            QcxMVp+eemq1u0ZxLla+nU+VTmYf9QVAdA4Esjx1/nCUWipeS/n7aLbRyjLZaE66
            /P1pstM6AcFI6YR98ffq6BYwqY0BZVO3HxeRKeLhKvr9vgjkw1+4De8i6cSuoJvu
            +yoTFwJSOezz9NlaOaVh7XGXIazNKzIz8eXrnU6snQxjGBEtywhpR4gu8RfUkwfU
            aAEJAhDrQN9TRVl+R3GkZsLyww+2xm2h9vqJ+YiaAXRkk9QIwLUNLipJ3uUW0vjT
            YdsiTGyDiGBI1th+W2hfbbUoFrwYgnba2qb7ha0oueTWBeAk0gNkijCKnfvGV/0U
            c1iFSal+5sZ5
            =mWlv
            -----END PGP MESSAGE-----
          fp: F811E22876B06D85B761DF92E3F5C8D6A1A7D6FB
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
