apiVersion: v1
kind: Secret
metadata:
    annotations:
        avp.kubernetes.io/path: secret.yaml
    name: encrypt-secret
    namespace: argocd
type: Opaque
data:
    key: ENC[AES256_GCM,data:syzxyA==,iv:PYQUSjo8jtdXtdFWJJ44xPDQ/2gtEDgeTtyTMM3l714=,tag:gYrovgodr6EXSFX5No+Mlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T10:57:42Z"
    mac: ENC[AES256_GCM,data:XT+ledCwr845t91bvk4MotSSL5pxdB/x1CoWym8q4Ft/1AfvWngXDmz+lEIAEVQsacTmwTeObb0hS35GgkTxocwEpsjtmcLPDIAz7H0/2FfO0D1yrw1LuKUFI9mfeWCuzWhAb67XB7y0aey9N80Z1CyoySN4E38gaSD9Gafe0/g=,iv:hFatyalfRl0+VKMYQLWQtv4yZ6cEY84r3MyD63gjm5I=,tag:5P2G4N0hem7ujlXh9lFkEg==,type:str]
    pgp:
        - created_at: "2025-01-28T10:57:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxofeBydO/LtARAAgy4CQfmMwyg8nR8hbq2J0EMEPsrG6Os3KCnBGfu0YIj6
            8t1Q2PA/Z60VkPlAR57UXOJR9JIZzRPSilcuErbICUprAfUAUpHqrjJUhH+iwSd6
            /mXW5ac6O4jj7oV8q7Um9nweyjVrSnmk0MoexsSATrRuUWX89w3LLEgWEew+/2aw
            pyl4Z8TL73o8OW/PP52P+LOvOli/bOT4KR3MR1/KtckT0dVFLeA16OI3HJZmRf2i
            O18k6VKU0fTJLEHNiYtbl4zcDMBR70wQRymxP8rY5WxWoiu2CwdN+0EhgBLsqGN6
            fL6i0+rzIn+n0zkHcqS3OgEsZD/Z3MDfDMa3YcX528g7I9rwuUVe2oq9Vnld8WkO
            3fVyz9jFwsSBH1V3aH8einqQbJmQgli2ebrsXSd5Pdi2jskOPUZSOJp0RbMxMaUi
            XImnDseoC193GU2yRADN1eVrvy5IXVYNS4PvnOkP3ta2SS7fOXDrlw2/lrCkeUnD
            iKsSHvqv4fAanG1FVvb4SYwJ1K0IHou71SKSgUaCeRuEbPVLuXXYnrIE3qU3Ie9/
            oQFbRh1qua/k+niqXcAnYrNR54neusUipuHoVrtntaqKh2PvTrcAHv6nxawnUD29
            lBnNQ6l+3+zY0dJKqmV0U6pHzbciTbXp52lc9Qx/5B/zLebQxOmgDkpXcCSToKPU
            aAEJAhBxmdXzFOftsyIvBUUJT7JM8qjvfFPjDnaK8PKDyZiYZATCYh1iXs2geMRO
            fVJCGdJJcBsbUwdkYfBf/dIV6PRZUuqoKyxH1gmT2DU5+q0B14HUOiYk/24UtNjl
            diKw9zK0m3c/
            =ALGX
            -----END PGP MESSAGE-----
          fp: F811E22876B06D85B761DF92E3F5C8D6A1A7D6FB
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
