apiVersion: v1
kind: Secret
metadata:
    annotations:
        avp.kubernetes.io/path: "secret.key.yaml"
    name: encrypt-secret
    namespace: sops
type: Opaque
stringData:
    keycloak.json: <keycloak.json>
    tiger.properties: <tiger.properties>
    server.xml: <server.xml>
